@startuml ServerClasses

skinparam {
    packageStyle rectangle
    Linetype ortho
    ClassAttributeIconSize 0
}

class "RouteHandler" as h <<domain>>
{
    RouteHandler(RouteCollection routes)
    + on_get_route() : auto
    + on_post_route() : auto
    -{static}init_resp(resp : RESP) : RESP
    -{static}mark_as_bad_request(auto& resp) : void
}

class "LogHandler" as l
{
    + append(log: string) : void
    + read() : string
    - fd_ : int
    - PATH_ : string
}


note left of h::on_get_route
Returns HTTP response
end note
note left of h::on_post_route
Returns HTTP response
end note

h --> l

@enduml