@startuml ServerClasses
mainframe **CD** Server

skinparam {
    packageStyle rectangle
    Linetype ortho
    ClassAttributeIconSize 0
}

class "RouteHandler" as h <<domain>>
{
    ' RouteHandler(route_collection_t)
    ' + on_get_route(req : reqrequest_handling_status_t) : auto
    ' + on_post_route(req : reqrequest_handling_status_t) : auto
    ' + options(req : reqrequest_handling_status_t) : auto
    ' - m_routes : route_collection_t
    ' -{static}init_resp(resp : RESP) : RESP
    ' -{static}mark_as_bad_request(auto& resp) : void


}

class "LogHandler" as l <<boundary>>
{
    ' + LogHandler(string)
    ' + post_route(string) : void
    ' + get_route() : string
    ' + update_route() : void
    ' + queue_empty() : bool
    ' - log_file : ofstrem
    ' - route_queue : deque<string>
    ' - file_path : string
}




h --> l

@enduml