@startuml SD UC2 - Create Delivery

mainframe **SD** UC2 - Create Delivery
hide footbox

actor "Dispensary Nurse" as dn <<actor>>
participant "Input" as in <<boundary>>
participant "TUI" as tui <<control>>
participant "Console" as cs <<boundary>>
participant "Button" as b <<boundary>>
participant "TextElement" as te <<boundary>>
participant "StatefulButton" as sb <<boundary>>
participant "HTTPHandler" as pc_http <<domain>>

'1. TUI active/open TUI
tui++ 

'2. TUI displays message and list of rooms
tui -> cs : setup()

'3.
cs++
cs--

'5.
tui -> tui: print_elements()

'6.
loop Tui:is_running()
dn ->> in : **Keybord button pressed**
tui -> in++ : update_input()
in -> in : read_input()
in -[hidden]-> in
in--
tui -> in++ : get_input()
in --> tui : key
in--
opt key == ENTER
tui -> b++ : action()
b--

end
tui -> tui : print_elements()
end 






@enduml