@startuml SD UC2 - Create Delivery - PC

<style>
note {
  MaximumWidth 150
}
</style>

mainframe **SD** PC
hide footbox

actor "Dispensary Nurse" as dn
participant main as main
participant "Input" as in <<boundary>>
participant "TUI" as tui <<control>>
participant "Console" as cs <<boundary>>
participant "Button" as b <<boundary>>
'participant "TextElement" as te <<boundary>>
'participant "StatefulButton" as sb <<boundary>>
participant "HTTPHandler" as http <<domain>>
actor "Server" as srv


tui -> cs : setup()

tui -> tui: print_elements()

loop Tui:is_running()

  main -> tui : update()
  dn ->> in : **Keybord button pressed**
  tui -> in : update_input()
  in -> in : read_input()
  'extra hidden arrow for plantuml aligment
  in -[hidden]-> in
  tui -> in : get_input() : Key
  in --> tui : key
  opt key == ENTER
    note over cs : This action function will vary depending on which button is actually selected in the UI. I.e. if you hit enter on the 'Confirm' button it'll send the HTTP request, or the 'Close UI' which closes the UI.
    tui -> b : action()

    note over http : This is for the specific case where the 'Confirm' button in the popup is selected

    b -> http : post(routes)
    http ->> srv : POST /new_route

  end
  tui -> tui : print_elements()
end

@enduml