@startuml domain_model

skinparam linetype ortho
skinparam rectangle {
    BackgroundColor White
    BorderColor Black
}

'   Entities

rectangle Server
rectangle TerminalUI
rectangle Car
rectangle Pathfinding
rectangle ActionButton
rectangle PowerButton
rectangle LED
rectangle Motor
actor DispensoryNurse
actor Nurse
rectangle HttpHandler
rectangle HttpHandler_Car
rectangle H_bridge
rectangle LogHandler

'   Relationships


DispensoryNurse --> ActionButton : press
Car --> ActionButton : monitor
DispensoryNurse --> PowerButton : press
PowerButton --> Car : ON/OFF
Nurse --> ActionButton : press
DispensoryNurse --> TerminalUI : select rooms
TerminalUI --> HttpHandler : create route
HttpHandler --> Server : send route

Server --> LogHandler : saves route
Car --> HttpHandler_Car : send request
HttpHandler_Car --> Server : request route
Server --> Pathfinding :  send route
Car --> Pathfinding : calculate path  

Car --> LED : has
Car --> H_bridge : instructions
H_bridge --> Motor : controls

LED --> Pathfinding : indicates

@enduml
