@startuml Project concept
mainframe **Rich image\t**

'Alternative fomatting
'left to right direction
'skinparam linetype ortho
skinparam maxmessagesize 50
skinparam MinClassWidth 50
'skinparam Padding 12

component "Server" as srv
component "Car" as car
component "Car controller" as carCon
component "Medicine storage" as meds
component "User interface" as ui
actor "User (nurse)" as usr
actor "Nurse 2" as nurse2
actor "Patient" as pat
component "New patient" as pat2


car -l-> nurse2 : Collects medicine
carCon -u-> srv : Notifies order completion
carCon -d-> car : Controls
meds -d-> usr : Receives medicine
nurse2 ---> car : Authenticates
nurse2 -u-> pat : Administers medicine
srv -d-> carCon : Gives delivery location
srv -d-> meds : Executes order
ui -d-> usr : Notifies fail/success
ui -u-> srv : Create order
usr -l-> car : Fills with medicine
usr -u-> ui : Orders medicine
carCon --> carCon : Pathfinds
pat2 -d-> srv : Arrives/Registers new location
srv -u-> srv : Update locations
srv --> carCon : Syncronises location map

' Keeps the right mainframe edge off the box
ui -[hidden]-> ui
@enduml