@startuml SystemSD UC2 - Create route
!pragma teoz true
mainframe **SD** UC2 - Create route
hide footbox

skinparam {
    MaxMessageSize 120
}

actor "Dispensary nurse" as dn

participant "**Terminal UI**" as ui
participant "**Server (RPi 1)**" as srv

srv++
dn ->> ui++ : Open UI
ui -> ui : Show UI

loop 1 to 3 times
    dn ->> ui : Select room to add
    opt Room is already selected
        ui -> ui : Deselect room
    end
    ui -> ui : Show updated selection
end

opt Cancel option selected
    ui -> ui : Close UI
end

dn ->> ui : Navigate to finish button and hit Enter key

opt No rooms added to route
    ui -> ui : Show "No rooms selected" msg

end

ui -> ui :  Show confirmation popup
alt Confirm option
    ui ->> srv : Send route information to server
    ui -> ui : route completion message appears
    & srv -> srv : Save route information to log file

else Deny option
    ui -> ui : Deselect all rooms
end
dn ->> ui : Press Enter key

ui -> ui : Close ui
|||
ui--

@enduml