@startuml SystemSD UC2 - Create order

mainframe **SD** UC2 - Create order
hide footbox

skinparam {
    MaxMessageSize 120
}


actor "Dispensary nurse" as dn

participant "**Terminal UI**" as ui
participant "**Server (RPi 1)**" as srv
participant "**Car**" as car
participant "**Car controller (RPi 2)**" as carCon
'participant "**HBridge**" as HBridge
'participant "**Motor**" as Motor

dn -> ui++ : Open UI
ui --> dn : Show UI

loop 1 to 3 times
    dn -> ui : Add rooms to order
end

dn -> ui : Navigate to finish button and hit Enter key
ui --> dn :  Show confirmation popup
dn -> ui : Hit confirm via Enter key

ui -> srv++ : Send order information to server
ui --> dn : Order completion message appears
ui--

srv -> srv++-- : Save order information to log file
car++
car -> srv : Notify ready to receive order
srv --> car : Send oldest order information
car -> carCon++ : Perform pathfinding
carCon -> carCon++-- : Turn on green light

@enduml