@startuml Actor-Context-Diagram
mainframe **Actor-Context Diagram\t**
skinparam MinClassWidth 100

left to right direction
actor "Nurse" as n
actor "Dispensary nurse" as dn


rectangle "Self driving delivery system" as car

dn --> car
car <-- n
@enduml